</section>
</div>
</div>
</main>

<!-- Footer section -->
<footer class="footer fixed-bottom py-3 bg-light">
    <div class="container">
        <!-- Simple footer text to describe the project-->
        <span class="text-muted">
YouthInvest By AJ Bell        </span>
    </div>
</footer>

<!-- Placed at the end so the pages load faster -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
        crossorigin="anonymous"></script>

<script src="../../js/movePlayerBoard.js"></script>

</body>
</html>