</section>
</div>
</div>
</main>

<footer class="footer py-4 bg-light mt-4">
    <div class="container d-flex justify-content-between align-items-start flex-wrap">

        <!-- LEFT SIDE: AJ Bell logo -->
        <div class="footer-left d-flex flex-column">
            <img src="/images/logo.png" alt="YouthInvest Logo" class="footer-logo mb-3">
        </div>

        <!-- CENTER TEXT -->
        <div class="footer-text text-muted">
            <p class="mb-1">Authorised and regulated by the Financial Conduct Authority.</p>
            <p class="mb-0">AJ Bell registered office: AJ Bell, 4 Exchange Quay, Salford Quays, Manchester, M5 3EE.</p>
        </div>

        <!-- RIGHT SIDE: SOCIAL ICONS -->
        <div class="footer-icons d-flex align-items-center gap-3 mt-3 mt-md-0">
            <i class="bi bi-youtube"></i>
            <i class="bi bi-twitter-x"></i>
            <i class="bi bi-linkedin"></i>
            <i class="bi bi-facebook"></i>
            <i class="bi bi-instagram"></i>
        </div>

    </div>
</footer>


<!-- Placed at the end so the pages load faster -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
        crossorigin="anonymous"></script>

<script src="/js/movePlayerBoard.js"></script>
<script src="/js/riskVisual.js"></script>


</body>
</html>